# Generated by Django 5.1.6 on 2025-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('survivor', 'Survivor'), ('provider', 'Service Provider'), ('law_enforcement', 'Law Enforcement')], default='survivor', max_length=20),
        ),
    ]
