# Generated by Django 3.2.23 on 2025-02-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_investigation', 'Under Investigation'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='case_evidence/')),
            ],
        ),
    ]
