# Generated by Django 5.1.6 on 2025-02-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casedocument_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedocument',
            name='title',
            field=models.CharField(default='Test Document', max_length=255),
            preserve_default=False,
        ),
    ]
