# Generated by Django 5.1.6 on 2025-02-23 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_casedocument_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselingsession',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counseling_sessions', to='cases.case'),
            preserve_default=False,
        ),
    ]
