# Generated by Django 5.1.6 on 2025-02-25 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_counselingsession_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='date_reported',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='case',
            name='assigned_provider',
        ),
        migrations.RemoveField(
            model_name='case',
            name='evidence_file',
        ),
        migrations.RemoveField(
            model_name='case',
            name='reporter',
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'law_enforcement'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='incident_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='incident_location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='incident_type',
            field=models.CharField(choices=[('physical', 'Physical Violence'), ('sexual', 'Sexual Violence'), ('emotional', 'Emotional/Psychological Violence'), ('economic', 'Economic Violence'), ('other', 'Other')], default='emotional', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='perpetrator_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='perpetrator_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='report_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='survivor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('under_investigation', 'Under Investigation'), ('medical_examination', 'Medical Examination'), ('legal_proceedings', 'Legal Proceedings'), ('closed', 'Closed')], default='reported', max_length=25),
        ),
        migrations.CreateModel(
            name='LawEnforcementAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('investigating', 'Investigating'), ('suspect_apprehended', 'Suspect Apprehended'), ('case_filed', 'Case Filed with Court'), ('closed', 'Closed')], default='assigned', max_length=25)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='law_enforcement_assignments', to='cases.case')),
                ('officer', models.ForeignKey(limit_choices_to={'user_type': 'law_enforcement'}, on_delete=django.db.models.deletion.PROTECT, related_name='law_enforcement_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
