# Generated by Django 5.1.6 on 2025-02-26 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_rename_date_reported_case_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'law_enforcement'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lawenforcementassignment',
            name='officer',
            field=models.ForeignKey(limit_choices_to={'role': 'law_enforcement'}, on_delete=django.db.models.deletion.PROTECT, related_name='law_enforcement_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
