# Generated by Django 5.1.6 on 2025-02-27 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_case_assigned_officer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='assigned_medic',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'medical_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_medic', to=settings.AUTH_USER_MODEL),
        ),
    ]
