# Generated by Django 5.1.6 on 2025-02-27 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_assigned_medic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawenforcementassignment',
            old_name='incident',
            new_name='case',
        ),
    ]
