# Generated by Django 5.1.6 on 2025-02-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0011_rename_incident_lawenforcementassignment_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawenforcementassignment',
            name='update_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
